POST http://localhost:8080/api/admin/lab
Content-Type: application/json

{
  "id": 903,
  "machineNumber": 70,
  "details": "null"
}
###
DELETE http://localhost:8080/api/admin/lab/906
###
GET http://localhost:8080/api/admin/teachers
###
POST http://localhost:8080/api/admin/teacher
Content-Type: application/json

{
  "id": 2018214254,
  "name": "王五",
  "profession": "信息与计算机工程学院"
}
###
DELETE http://localhost:8080/api/admin/teacher/2018214255
###
PATCH http://localhost:8080/api/admin/teacher
Content-Type: application/json

{
  "tid": 2018214255,
  "name": "赵六",
  "profession": "信息与计算机工程学院"
}
###
POST http://localhost:8080/api/admin/user
Content-Type: application/json

{
  "id": 1,
  "role": 9,
  "userName": "admin",
  "password": "admin"
}
###